dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink@1.4.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@chainlink=smartcontractkit/chainlink@1.4.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}